apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "postgres.fullname" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "false"
provisioner: {{ .Values.provisioner }}
parameters:
  {{- if eq .Values.global.provisioner "kubernetes.io/aws-ebs" }}
  type: gp2
  fsType: {{ .Values.global.fsType }}
  {{- else if eq .Values.global.provisioner "kubernetes.io/gce-pd" }}
  type: {{ .Values.global.gcePdStorageType }}
  #TODO: add minikube or microk8s host provisioner
  {{- end }}
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: {{ .Values.global.reclaimPolicy }}
mountOptions:
  - debug
