apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.fullname" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.global.secret.dbPass | b64enc }}
  # POSTGRES_USER: {{ .Values.global.secret.dbUser | b64enc }}
  # POSTGRES_DATABASE: {{ .Values.global.secret.dbName | b64enc }}