apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api-chart.fullname" . }}
  labels:
    {{- include "api-chart.labels" . | nindent 4 }}
data:
  MAIL_SERVER: {{ .Values.configMap.mailServer | quote }}
  MAIL_PORT: {{ .Values.configMap.mailPort | quote }}
  MAIL_USE_TLS: {{ .Values.configMap.mailUseTLS | quote }}
  MAIL_USE_SSL: {{ .Values.configMap.mailUseSSL | quote }}
  APP_SETTINGS: {{ .Values.configMap.appSettings | quote }}
  