apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api-chart.fullname" . }}
  labels:
    {{- include "api-chart.labels" . | nindent 4 }}
data:
  MAIL_SERVER: {{ .Values.configmap.mailServer | quote }}
  MAIL_PORT: {{ .Values.configmap.mailPort | quote }}
  MAIL_USE_TLS: {{ .Values.configmap.mailUseTLS | quote }}
  MAIL_USE_SSL: {{ .Values.configmap.mailUseSSL | quote }}
  APP_SETTINGS: {{ .Values.configmap.appSettings | quote }}
  DB_PORT: {{ .Values.configmap.dbPort | quote }}
  