apiVersion: v1
kind: Secret 
metadata:
  name: {{ include "api-chart.fullname" . }}
  labels:
    {{- include "api-chart.labels" . | nindent 4 }}
type: Opaque
data:
  SECRET_KEY: {{ .Values.secret.secretKey | b64enc }}
  SECURITY_PASSWORD_SALT: {{ .Values.secret.securityPasswordSalt | b64enc }}
  SECURITY_PASSWORD_RESET_SALT: {{ .Values.secret.securityPasswordResetSalt | b64enc }}
  APP_MAIL_USERNAME: {{ .Values.secret.appMailUsername | b64enc }}
  APP_MAIL_PASSWORD: {{ .Values.secret.appMailPassword | b64enc }}
  MAIL_DEFAULT_SENDER: {{ .Values.secret.mailDefaultSender | b64enc }}
  DB_PASS: {{ .Values.global.secret.dbPass | b64enc }}
  DB_USER: {{ .Values.global.secret.dbUser | b64enc }}
  DB_NAME: {{ .Values.global.secret.dbName | b64enc }}
  DB_HOST: {{ .Values.secret.dbHost | b64enc }}
  DB_PORT: {{ .Values.secret.dbPort | b64enc }}