apiVersion: v1
kind: Secret 
metadata:
  name: {{ include "api-chart.fullname" . }}
  labels:
    {{- include "api-chart.labels" . | nindent 4 }}
data:
  DATABASE_URL: {{ .Values.secret.databaseURL | b64enc }}
  SECRET_KEY: {{ .Values.secret.secretKey | b64enc }}
  SECURITY_PASSWORD_SALT: {{ .Values.secret.securityPasswordSalt | b64enc }}
  SECURITY_PASSWORD_RESET_SALT: {{ .Values.secret.securityPasswordResetSalt | b64enc }}
  APP_MAIL_USERNAME: {{ .Values.secret.appMailUsername | b64enc }}
  APP_MAIL_PASSWORD: {{ .Values.secret.appMailPassword | b64enc }}
  MAIL_DEFAULT_SENDER: {{ .Values.secret.mailDefaultSender | b64enc }}