apiVersion: v2
name: helm
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
type: application
version: 0.1.0
appVersion: 1.16.0
maintainers:
  - name: M@os
email: kungusamuel90@gmail.com
