{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress 
metadata:
  name: {{ include "ingress.fullname" . }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: api.maos.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: 
                name: api-chart
                port:
                  number: 5000
 
{{- end }}
